---
- name: Install docker
  gather_facts: No
  hosts: microserversgroup

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
