---
- name: Install nginx
  hosts: microserversgroup
  become: true

  tasks:
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Start NGiNX
    service:
      name: nginx
      state: started
